apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-deployment
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-app
  template:
    metadata:
      labels:
        app: nextcloud-app
    spec:
      containers:
      - name: nextcloud
        image: nextcloud:stable-apache
        volumeMounts:
          - mountPath: /var/www/html
            name: server-storage
            subPath: data
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      volumes:
      - name: server-storage
        persistentVolumeClaim:
          claimName: ps-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-entrypoint
spec:
  type: NodePort
  selector:
    app: nextcloud-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001